### ISSUE TITLE
Just opening the app

### ISSUE THREAD

**Issue by islam2hamy** [votacom/octalsuntime#37]
FATAL EXCEPTION: main
Process: at.manuelbichler.octalsuntime, PID: 15525
java.lang.NoSuchMethodError: No virtual method toInstant()Ljava/time/Instant; in class Ljava/util/Date; or its super classes (declaration of 'java.util.Date' appears in /system/framework/core-oj.jar)
	at at.manuelbichler.octalsuntime.MainActivity.getRelativeTime(MainActivity.kt:154)
	at at.manuelbichler.octalsuntime.MainActivity.updateTimes(MainActivity.kt:143)
	at at.manuelbichler.octalsuntime.MainActivity.updateClock(MainActivity.kt:192)
	at at.manuelbichler.octalsuntime.MainActivity.updateLocation(MainActivity.kt:172)
	at at.manuelbichler.octalsuntime.MainActivity.onCreate(MainActivity.kt:135)
	at android.app.Activity.performCreate(Activity.java:6857)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2676)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by islam2hamy** [comment]
Version 0.1.3
Android 7.1.2

**Comment by votacom** [comment]
Thanks for the report. Can you check if the exception also occurs in a more recent version if the app? (A lot has changed since 0.1.3)

**Comment by votacom** [comment]
Oh, I see you are using Android 7. Unfortunately, stable versions of the app (v0.2.0 and up) only support Android 8 and up.

=> won't fix.
